define([], function () {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "FormLabelDocumentTitle": "Document Title",
    "FormLabelDocumentNumber": "Document Number",
    "FormLabelDocumentType": "Document Type",
    "FormLabelProcessOptions": "Process Options",
    "FormLabelAreaofValidity": "Area of Validity",
    "FormLabeldocumentTypeOptions": "Document Type Options",
    "FormLabelRegion": "Region",
    "FormLabelPlant": "Plant",
    "FormLabelDepartment": "Department",
    "FormLabelHeritageNumber": "Heritage Number",
    "FormLabelVersionNumber": "Version Number",
    "FormLabelISOStandardOptions": "ISO Standard Options",
    "FormLabelISOStandardElementChapterOptions": "ISO Standard Element ChapterOptions",
    "FormLabelKeywords": "Keywords",
    "FormLabelBusinessLineOptions": "Business Line Options",
    "FormLabelDurationOfArchiving": "Duration Of Archiving",
    "FormLabelEHSRelevant": "EHS Relevant",
    "FormLabelReadingConfirmation": "Reading Confirmation",
    "FormLabelBusinessProcessOwner": "Business Process Owner(BPO)",
    "FormLabelVerifier": "Verifier",
    "FormLabelReleaser": "Releaser",
    "FormLabelAuthor": "Author",
    "FormLabelRemarksForWorkflowMails": "Label Remarks For Workflow Mails",
    "FormLabelReminderWorkflowSteps":"Reminder Workflow Steps",
    "FormLabelReminderWorkflowStepsforAuthor": "Reminder WorkflowSteps for Author",
    "FormLabelReminderWorkflowStepsforVerifer": "Reminder WorkflowSteps for Verifer",
    "FormLabelReminderWorkflowStepsforReleaser": "Reminder WorkflowSteps for Releaser",
    "FormLabelReminderWorkflowStepsforDistributor": "Reminder WorkflowSteps for Distributor",
    "FormLabelRevisionInterval": "Revision Interval",
    "FormLabelReminderRevisionInterval": "Reminder Revision Interval",
    "FormLabelValidFrom": "Valid From",
    "FormLabelValidUntil": "Valid Until",
    "FormLabelPrintInformationValidityOnDayOfPrintingOnly": "Print InFormation Validity On Day Of Printing Only",
    "FormLabelDistributionList": "Distribution list",
    "FormLabelPendingReaderConfirmation": "Pending Reader Confirmation",
    "FormLabelContent": "Content",
    "FormLabelAdditionalApplicableDocuments": "Additional Applicable Documents",
    "FormLabelProofOfTraining": "Proof Of Training",
    "FormLabelStatusofDocument": "Status of Document",
    "FormLabelMarkOfChangeText": "Mark Of Change Text",
    "FormLabelReferToStandardInCaseOfTestProcedures": "Refer To Standard InCase Of Test Procedures",
    "FormLabelCommentsOfReadersToTheDocument": "Comments Of Readers To The Document",
    "FormLabelDateOfArchive": "Date Of Archive",
    "FormLabelDateOfRelease": "Date Of Release",
    "FormLabelDateOfNextRevision": "Date Of Next Revision",
    "FormLabelCommentHistory": "Comment History",
    "FormLabelAttachment": "Attachment",



  }
});