define([], function () {
    return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "FormLabelDocumentTitle": " Titre du document",
    "FormLabelDocumentNumber": "Numéro de document",
    "FormLabelDocumentType": "Type de document",
    "FormLabeldocumentTypeOptions":"Process",
    "FormLabelProcessOptions":"Process",
    "FormLabelAreaofValidity": "Domaine de validité",
    "FormLabelRegion":"Région",
    "FormLabelPlant":"Usine",
    "FormLabelDepartment":"French Department",
    "FormLabelHeritageNumber":"Numéro précédent du document",
    "FormLabelVersionNumber":"Numéro de la version",
    "FormLabelISOStandardOptions":"Norme ISO",
    "FormLabelISOStandardElementChapterOptions":"Element / Chapitre de la norme",
    "FormLabelKeywords":"Mots clés",
    "FormLabelBusinessLineOptions":"Secteur d'activités",
    "FormLabelDurationOfArchiving":"Durée d'archivage",
    "FormLabelEHSRelevant":"Pertinence pour l'HSE",
    "FormLabelReadingConfirmation": "Confirmation de lecture",
    "FormLabelBusinessProcessOwner":"Propriétaire du document",
    "FormLabelAuthor":"Auteur",
    "FormLabelVerifier":" Verificateur",
     "FormLabelReleaser":"Approbateur",
    "FormLabelRemarksForWorkflowMails":"Notes pour le flux de mail",
    "FormLabelReminderWorkflowSteps":"Reminder Workflow Steps",
    "FormLabelReminderWorkflowStepsforAuthor":"Rappel des étapes Auteur",
  "FormLabelReminderWorkflowStepsforVerifer":"Rappel des étapes Verificateur",
    "FormLabelReminderWorkflowStepsforReleaser": "Rappel des étapes Approbateur",
    "FormLabelReminderWorkflowStepsforDistributor":"Rappel des étapes Distributor",
    "FormLabelRevisionInterval":"Intervalle de révision",
    "FormLabelReminderRevisionInterval":"Rappel des intervalles de révision",
    "FormLabelValidFrom":"Valable à partir de ",
    "FormLabelValidUntil":"Valable jusqu'à",
    "FormLabelPrintInFormationValidityOnDayOfPrintingOnly":"Document valable uniquement le jour de l'impression",
    "FormLabelDistributionList":"Liste de distribution",
    "FormLabelPendingReaderConfirmation":"Ouvert à la lecture",
    "FormLabelContent":"Contenu",
    "FormLabelAdditionalApplicableDocuments":"Document supplémentaire applicable",
    "FormLabelProofOfTraining":"Preuve de formation",
    "FormLabelStatusofDocument":"Statut du document",
   "FormLabelMarkOfChangeText":"Preuves de changement",
   "FormLabelReferToStandardInCaseOfTestProcedures":"Se référer à la norme en cas de procédures de test",
   "FormLabelCommentsOfReadersToTheDocument":"Commentaires des lecteurs",
    "FormLabelDateOfArchive":"French Date Of Archive",
    "FormLabelDateOfRelease":"French Date Of Release",
    "FormLabelDateOfNextRevision":"French Date Of Next Revision",
     "FormLabelCommentHistory":"French Comment History",
     "FormLabelAttachment":"French Attachment",
     
    
    }
  });